import localFont from 'next/font/local';
import './globals.css';
import { ShopProvider } from '@/context/ShopContext';
import ResponsiveNavbar from '@/components/Header';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Shop on Track',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShopProvider>
          <ResponsiveNavbar />
          {children}
          <Footer />
        </ShopProvider>
      </body>
    </html>
  );
}
